### ISSUE TITLE
Push code upstream

### ISSUE THREAD

**Issue by mzamani1** [dropwizard/dropwizard-redis#1]
This one will take me a bit longer to get in contribution state, as I need to clean up my internal code to no longer use our internal Redis client, and move to using Jedis instead.

**Comment by joschi** [comment]
@mzamani1 It's my subjective opinion, but I think using [Lettuce](https://lettuce.io/) instead of Jedis would be nice, because the former is quite well maintained and also used in the Spring ecosystem.

https://github.com/lettuce-io/lettuce-core

**Comment by mzamani1** [comment]
@joschi definitely not opposed to that! Do you think it’d make sense to support both, or do you think lettuce is just a superior Redis client that would make more sense to be the one supported?

**Comment by joschi** [comment]
@mzamani1 I think supporting one Redis client library very well instead of multiple client libraries makes most sense.

**Comment by mzamani1** [comment]
@joschi let me take a closer look at lettuce this weekend.
