### ISSUE TITLE
Switch to supporting Lettuce from Jedis

### ISSUE THREAD

**Issue by mzamani1** [dropwizard/dropwizard-redis#2]
At the suggestion from @joschi (in #1) and doing some further research (despite it's clear bias, this is a convincing argument, that I _assume_ is still true enough:
https://github.com/spring-projects/spring-session/issues/789#issuecomment-303709315), I think it'd be wise to support lettuce (https://github.com/lettuce-io/lettuce-core) over Jedis.

**Comment by joschi** [comment]
Regarding the question why using Lettuce over Jedis might be a good idea, see also
[this blog article (translated with Google Translate)](https://translate.google.com/translate?hl=&sl=ko&tl=en&u=https%3A%2F%2Fjojoldu.tistory.com%2F418) by @jojoldu.

**Comment by mzamani1** [comment]
I'm convinced. :) 

I'm going to start with support for the cluster client. I'd love some help covering the other client types as well (Sentinel and Master/Replica).

**Comment by mzamani1** [comment]
Released in https://github.com/dropwizard/dropwizard-redis/releases/tag/dropwizard-redis-1.3.12-1
