### ISSUE TITLE
New release to update a library?

### ISSUE THREAD

**Issue by gabrieeel** [dropwizard/dropwizard-redis#96]
Hi, is it possible to merge this PR (https://github.com/dropwizard/dropwizard-redis/pull/95) to master and create a new release? 
From lettuce-core 6.1 onwards, there are several redis commands included such as getdel, getex, etc. Thanks!

**Comment by joschi** [comment]
dropwizard-redis 1.5.2 has been released and should hit Maven Central soon:
https://github.com/dropwizard/dropwizard-redis/releases/tag/dropwizard-redis-1.5.2
